# Generated by Django 3.1.3 on 2023-08-28 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testlab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testlab',
            options={'verbose_name': 'Test Lab', 'verbose_name_plural': 'Test Lab'},
        ),
    ]
