# Generated by Django 3.1.3 on 2023-08-28 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testlab', '0003_testlab_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testlab',
            name='description',
        ),
    ]
