# Generated by Django 3.1.3 on 2023-08-26 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('vendor', models.CharField(max_length=255)),
                ('email_vendor', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('NOK', 'NOK')], max_length=3)),
                ('note', models.CharField(max_length=2000)),
                ('has_license', models.BooleanField(default=False)),
                ('version', models.CharField(blank=True, max_length=30, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=20, null=True)),
                ('last_revision_at', models.DateField(blank=True, null=True)),
                ('has_not_calibration', models.BooleanField()),
                ('last_calibration_at', models.DateField(blank=True, null=True)),
                ('last_calibration_by', models.CharField(blank=True, max_length=255, null=True)),
                ('cabinet', models.PositiveIntegerField()),
                ('shelf', models.PositiveIntegerField()),
                ('last_revision_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
            },
        ),
    ]
