# Generated by Django 3.1.3 on 2023-08-26 16:54

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='has_not_calibration',
            new_name='has_calibration',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='last_calibration_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
