# Generated by Django 3.1.3 on 2023-08-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20230826_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='shelf',
        ),
    ]
