# Generated by Django 3.1.3 on 2023-08-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_auto_20230830_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='last_calibration_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
