# Generated by Django 3.1.3 on 2023-08-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_auto_20230830_1915'),
        ('department', '0004_auto_20230830_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='department',
            name='shelf',
        ),
        migrations.AddField(
            model_name='department',
            name='equipment',
            field=models.ManyToManyField(to='equipment.Equipment'),
        ),
    ]
